"""empty message

Revision ID: 379d3364b56d
Revises: ad36542c2a92
Create Date: 2019-11-11 21:47:55.863096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379d3364b56d'
down_revision = 'ad36542c2a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
