"""empty message

Revision ID: 8b3acefdeeed
Revises: 379d3364b56d
Create Date: 2019-12-19 17:14:15.127888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3acefdeeed'
down_revision = '379d3364b56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('employee_function', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'employee_function')
    # ### end Alembic commands ###
