"""empty message

Revision ID: ad36542c2a92
Revises: da26961e4824
Create Date: 2019-10-14 20:04:21.101802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad36542c2a92'
down_revision = 'da26961e4824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('cep', sa.String(length=255), nullable=True))
    op.add_column('address', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('address', sa.Column('neighborhood', sa.String(length=255), nullable=True))
    op.add_column('address', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('uf', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'uf')
    op.drop_column('address', 'number')
    op.drop_column('address', 'neighborhood')
    op.drop_column('address', 'city')
    op.drop_column('address', 'cep')
    # ### end Alembic commands ###
