"""empty message

Revision ID: b63f0cb5e209
Revises: 09553e89e72f
Create Date: 2019-10-13 21:53:41.351853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63f0cb5e209'
down_revision = '09553e89e72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('birth_date', sa.DateTime(timezone=20), nullable=True))
    op.add_column('employee', sa.Column('cpf', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'cpf')
    op.drop_column('employee', 'birth_date')
    # ### end Alembic commands ###
