"""empty message

Revision ID: b71422fd2e16
Revises: f6219d89a3fe
Create Date: 2019-06-21 08:02:36.638809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71422fd2e16'
down_revision = 'f6219d89a3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['movement.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['movement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movement_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], ['movement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movement_value')
    op.drop_table('movement_employee')
    op.drop_table('movement_description')
    op.drop_table('movement')
    op.drop_table('expense')
    # ### end Alembic commands ###
