"""empty message

Revision ID: da26961e4824
Revises: d574f4eb0787
Create Date: 2019-10-14 20:04:01.568574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da26961e4824'
down_revision = 'd574f4eb0787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'city')
    op.drop_column('address', 'cep')
    op.drop_column('address', 'uf')
    op.drop_column('address', 'neighborhood')
    op.drop_column('address', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('neighborhood', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('uf', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('cep', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('city', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
