"""empty message

Revision ID: e637bd27fa42
Revises: 7a9b4951bb46
Create Date: 2019-10-14 19:47:55.943846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e637bd27fa42'
down_revision = '7a9b4951bb46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'cpf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('cpf', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
